import { Product } from "@/types/product";

const Data: Product[] = [
  {
    id: "1",
    name: "iPhone 12",
    price: 699,
    quantity: 0,
    category: "Smartphone",
  },
  {
    id: "2",
    name: "iPhone 12 Pro",
    price: 999,
    quantity: 3,
    category: "Smartphone",
  },
  {
    id: "3",
    name: "iPhone 12 Pro Max",
    price: 1099,
    quantity: 12,
    category: "Smartphone",
  },
  {
    id: "4",
    name: "Samsung Galaxy S20",
    price: 799,
    quantity: 8,
    category: "Smartphone",
  },
  {
    id: "5",
    name: "Samsung Galaxy S10",
    price: 699,
    quantity: 0,
    category: "Smartphone",
  },
  {
    id: "6",
    name: "Samsung Galaxy S20 Ultra",
    price: 999,
    quantity: 2,
    category: "Smartphone",
  },
  {
    id: "7",
    name: "Huawei P30",
    price: 499,
    quantity: 25,
    category: "Smartphone",
  },
  {
    id: "8",
    name: "Huawei P40",
    price: 599,
    quantity: 17,
    category: "Smartphone",
  },
  {
    id: "9",
    name: "Nokia 3310",
    price: 399,
    quantity: 42,
    category: "Smartphone",
  },
  {
    id: "10",
    name: "iPad Air",
    price: 599,
    quantity: 4,
    category: "Tablet",
  },
  {
    id: "11",
    name: 'iPad Pro 11"',
    price: 899,
    quantity: 0,
    category: "Tablet",
  },
  {
    id: "12",
    name: "Samsung Galaxy Tab S7",
    price: 649,
    quantity: 9,
    category: "Tablet",
  },
  {
    id: "13",
    name: "MacBook Air M1",
    price: 999,
    quantity: 6,
    category: "Laptop",
  },
  {
    id: "14",
    name: 'MacBook Pro 14"',
    price: 1999,
    quantity: 2,
    category: "Laptop",
  },
  {
    id: "15",
    name: "Dell XPS 13",
    price: 1249,
    quantity: 5,
    category: "Laptop",
  },
  {
    id: "16",
    name: "AirPods Pro",
    price: 249,
    quantity: 30,
    category: "Audio",
  },
  {
    id: "17",
    name: "Sony WH-1000XM4",
    price: 349,
    quantity: 0,
    category: "Audio",
  },
  {
    id: "18",
    name: "JBL Flip 5",
    price: 119,
    quantity: 14,
    category: "Audio",
  },
  {
    id: "19",
    name: "Apple Watch Band",
    price: 49,
    quantity: 60,
    category: "Accessories",
  },
  {
    id: "20",
    name: "USB-C Charger 20W",
    price: 19,
    quantity: 100,
    category: "Accessories",
  },
];

export default Data;
